services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    volumes:
      - ./database:/app/database
    env_file:
      - .env