version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[p]ython main.py' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
